# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
include:
# redox
  - board: nrfmicro/nrf52840
    shield: redox_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: redox_left
  - board: nrfmicro/nrf52840
    shield: redox_right
    artifact-name: redox_right
  - board: nrfmicro/nrf52840
    shield: settings_reset
    artifact-name: settings_reset

# sofle
  - board: nice_nano
    shield: sofle_left nice_view_adapter nice_view_gem
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: sofle_left
  - board: nice_nano
    shield: sofle_right nice_view_adapter nice_view_gem
    artifact-name: sofle_right
  - board: nice_nano
    shield: settings_reset
